Repository sudiptasarkar011/FusionVision, pull requests merged in 2025-02, with the labels that each got.

#96 Add Contributor page
  contributor.css
  contributor.html
  contributor.js
  index.html
Labels: ⁠Intermediate, SWOC

#101 added light and dark mode
  about.html
  contact.html
  features.html
  index.html
  reviews.html
  script.js
  styles.css
Labels: IWOC2025, Medium

#102 ✨ Fixed Background of Sign-in and Sign-up Pages ✨
  .vscode/settings.json
  about.html
  contact.html
  features.html
  index.html
  reviews.html
  script.js
  signIn.html
  signUp.html
  styles.css
Labels: ⁠Intermediate, SWOC

#108 Add Standardized Issue and Pull Request Templates (Closes #105)
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question_and_support.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: IWOC2025, Medium

#111 sigin and signup using express and jwt and express done (closes #106)
  login.js
  package-lock.json
  package.json
  script.js
  server.js
  signIn.html
  signUp.html
  signup.js
Labels: IWOC2025, Hard

#120 package.json updated (#109)
  package-lock.json
  package.json
Labels: IWOC2025, Easy

#123 Authentication using Cookies in Login route
  .env
  package.json
  server.js
  utils.js
Labels: IWOC2025, Hard

#128 Updated container alignment of who we are page
  styles.css
  whoweare.html
Labels: Beginner, SWOC

#130 Organized the files
  .github/CONTRIBUTING.md
  .github/README.md
  .vscode/.gitignore
  .vscode/package-lock.json
  .vscode/package.json
  about/about.html
  about/contact/contact.html
  about/features/features.html
  about/reviews/reviews.html
  camera/camera.html
  camera/camera.js
  camera/capture.js
  camera/models.js
  camera/object-detection.js
  footer_elements/Terms.html
  footer_elements/blog.html
  footer_elements/contributor/contributor.css
  footer_elements/contributor/contributor.html
  footer_elements/contributor/contributor.js
  footer_elements/privacyp.html
  footer_elements/whoweare.html
  footer_elements/workwithus.html
  images/FusionVision_BG.jpg
  images/FusionVision_BG_blurred.jpg
  images/Logo.png
  images/contact.jpg
  images/homepage.jpg
  images/iwoc.png
  images/permission.jpg
  images/swoc.png
  index.html
  login/auth.js
  login/login.js
  login/signIn.html
  login/signUp.html
  login/signup.js
  privacyp.html
  styles.css
  workwithus.html
Labels: IWOC2025, Easy

#134 enhanced sign-in and sign-up page
  .github/README.md
  about/contact/contact.html
  about/features/features.html
  login/signIn.html
  login/signUp.html
  login/signin.html
Labels: IWOC2025, Medium

#141 changed text color
  index.html
Labels: Beginner, SWOC

#143 Updated Navigation and Footer Text Color for Dark Mode
  index.html
  styles.css
Labels: ⁠Intermediate, SWOC
