Repository sudiptasarkar011/FusionVision, pull requests merged in 2025-01, with the labels that each got.

#17 Updating Footer Section
  about.html
  camera.html
  contact.html
  index.html
  styles.css
Labels: Beginner, SWOC

#21 #19adding social media icons in about.html,contact.html
  about.html
  contact.html
Labels: Beginner, SWOC

#30 issue-#15
  FusionVision_BG.jpg
  FusionVision_BG_blurred.jpg
  about.html
  camera.html
  contact.html
  index.html
  styles.css
Labels: ⁠Intermediate, SWOC

#32 Added Testimonials page
  index.html
  reviews.html
Labels: ⁠Intermediate, SWOC

#34 Implemented database integration for user credentials and image metadata
  .gitignore
  db.js
  models.js
  package-lock.json
  package.json
  server.js
Labels: Advanced, SWOC

#62 cursor trail effect added
  about.html
  camera.html
  contact.html
  features.html
  index.html
  privacyp.html
  reviews.html
  whoweare.html
Labels: Beginner, SWOC

#63 Updated UI of Contact page
  about.html
  camera.html
  contact.html
  features.html
  index.html
  privacyp.html
  reviews.html
Labels: Beginner, SWOC

#64 Added hover to buttons of scanner controls and icons and links to follow us section in footer
  camera.html
Labels: Beginner, SWOC

#66 Add Scroll-to-Top Button to Homepage
  index.html
  script.js
  styles.css
Labels: ⁠Intermediate, SWOC

#67 Add terms of Service page
  Terms.html
  index.html
Labels: Beginner, SWOC

#74 Resolved issues on the reviews.html page. Updated the navbar and footer.
  reviews.html
Labels: Beginner, SWOC

#79 changed features style #73
  features.html
  styles.css
Labels: Beginner, SWOC

#80 updated all footers
  about.html
  contact.html
  features.html
  index.html
  privacyp.html
  reviews.html
  styles.css
Labels: Beginner, IWOC2025

#92 fixed term file
  Terms.html
  about.html
  contact.html
  features.html
Labels: IWOC2025, Easy

#94 fixed
  features.html
  reviews.html
  styles.css
Labels: IWOC2025, Medium
